import fitz
import json
import re
from pathlib import Path

PDF_FILE = Path("caau.pdf")
OUTPUT_FILE = Path("output/artUnits.json")
RANGE_TOKEN = (
    r"(?:"
    r"FOR\s+\d+"
    r"|DIG\s+\d+"
    r"|E\d+(?:\.\d+)?"
    r"|[0-9]+(?:\.[0-9]+)?(?:\s+[A-Z])?"
    r"|ALL"
    r")"
)

DEBUG_CLASS = "358"
DEBUG_FILE = Path("debug358.txt")

def extract_pdf_text():

    print("Reading PDF...")

    if not PDF_FILE.exists():

        raise FileNotFoundError(
            f"{PDF_FILE} not found."
        )

    pages = []

    with fitz.open(PDF_FILE) as document:

        for page in document:

            pages.append(  page.get_text() )

    return "\n".join(pages)


def parse_range_line(line):

	line = line.rstrip()
	
	#
	# ALL
	#
	
	if line == "ALL":
	
		return (
			"",
			{
				"from": "ALL",
				"to": "ALL"
			}
		)
	
	#
	# title + from + to
	#
	
	match = re.match(
	
		rf"^(.*?)\s{{2,}}({RANGE_TOKEN})\s{{2,}}({RANGE_TOKEN})$",
	
		line
	
	)
	
	if match:
	
		return (
	
			match.group(1).strip(),
	
			{
	
				"from": match.group(2).strip(),
	
				"to": match.group(3).strip()
	
			}
	
		)
	
	#
	# title + single range
	#
	
	match = re.match(
	
		rf"^(.*?)\s{{2,}}({RANGE_TOKEN})$",
	
		line
	
	)
	
	if match:
	
		#
		# If the "title" is itself a range token,
		# this is really "from + to".
		#
	
		left = match.group(1).strip()
	
		if re.fullmatch(
			RANGE_TOKEN,
			left
		):
	
			return (
	
				"",
	
				{
	
					"from": left,
	
					"to": match.group(2).strip()
	
				}
	
			)
	
		return (
	
			left,
	
			{
	
				"from": match.group(2).strip(),
	
				"to": ""
	
			}
	
		)
	
	#
	# from + to
	#
	
	match = re.match(
	
		rf"^({RANGE_TOKEN})\s{{2,}}({RANGE_TOKEN})$",
	
		line
	
	)
	
	if match:
			
		return (
	
			"",
	
			{
	
				"from": match.group(1).strip(),
	
				"to": match.group(2).strip()
	
			}
	
		)
	
	#
	# single value
	#
	
	value = line.strip()
	
	if re.fullmatch(
	
		RANGE_TOKEN,
	
		value
	
	):
	
		return (
	
			"",
	
			{
	
				"from": value,
	
				"to": ""
	
			}
	
		)
	
	return None
	

def should_skip_line(line):

    line = line.strip()

    if not line:

        return True

    skip_patterns = [

        r"^November",

        r"^Generated by:",

        r"^CLASSES ARRANGED BY ART UNIT",

        r"^[IVX]+\s*-\s*\d+$",

        r"^Class Title$",

        r"^Subclass Ranges$",

        r"^From\s+To$",

        r"^Art Unit$",

        r"^Class$",

        r"^-+(\s+-+)*$"

    ]

    for pattern in skip_patterns:

        if re.match( pattern, line, re.IGNORECASE ):
            return True

    return False


def parse_art_unit(line):

    line = line.strip()

    match = re.match(  r"^Art Unit\s+(\d+)$", line, re.IGNORECASE )

    return match.group(1) if match else None


def parse_class(line):

    line = line.strip()

    match = re.match(
        r"^Class\s+([A-Z]?\s*\d+[A-Z]?|[A-Z]{2,}\d*|[A-Z]\d+[A-Z]?)\s+(.*)$",
        line,
        re.IGNORECASE
    )

    if not match:
        return None

    class_id = match.group(1).strip()
    remainder = match.group(2)

    range_match = re.search(
        rf"^(.*?)\s{{2,}}({RANGE_TOKEN})(?:\s{{2,}}({RANGE_TOKEN}))?$",
        remainder
    )

    if not range_match:
        return class_id, remainder.strip(), None

    return (
        class_id,
        range_match.group(1).strip(),
        {
            "from": range_match.group(2).strip(),
            "to": range_match.group(3).strip() if range_match.group(3) else ""
        }
    )
 

def add_range(art_units, current_class, current_art_unit, range_data):

    range_data["artUnit"] = current_art_unit
    art_units[current_class]["ranges"].append(range_data)

def add_first_range(art_units, current_class, current_art_unit, first_range):

    if first_range is not None:
        add_range( art_units, current_class, current_art_unit,  first_range)
    
    
def report_unrecognized( current_art_unit, current_class, current_title, line):

    print(
        f"\nUNRECOGNIZED\n"
        f"Art Unit : {current_art_unit}\n"
        f"Class    : {current_class}\n"
        f"Title    : {current_title}\n"
        f"Line     : {line}\n"
        f"Warning: Unrecognized line: {line}"
    )
    
    
def write_debug_file(debug_lines):
    DEBUG_FILE.write_text("\n".join(debug_lines), encoding="utf-8")
    

def normalize_whitespace(text):

    return " ".join(  text.split() )

def append_title_fragment(current_title, fragment, art_units, current_class):

    fragment = normalize_whitespace(fragment)
    current_title = normalize_whitespace(current_title)

    if not current_title.endswith(fragment):
        current_title += f" {fragment}"

    art_units[current_class]["title"] = current_title

    return current_title



def create_class(art_units, class_id, title):

    art_units[class_id] = { "title": title, "ranges": [] }
    

def start_new_art_unit( art_unit):

    return ( art_unit, None,  "", False, False)
    

def handle_new_art_unit( line, current_class, debug_lines):

    art_unit = parse_art_unit( line)

    if not art_unit:

        return None

    if current_class == DEBUG_CLASS:

        debug_lines.extend(
            [
                "",
                "=" * 70,
                f"NEW ART UNIT {art_unit}",
                "=" * 70
            ]
        )

    return start_new_art_unit( art_unit )
    

def initialize_class( art_units, current_class, current_title):

    if current_class not in art_units:

        create_class( art_units, current_class, current_title)

    else:

        current_title = art_units[current_class ][ "title"]

    return current_title
    
def handle_new_class( line, art_units, current_art_unit, debug_lines):

    parsed_class = parse_class( line )

    if not parsed_class:

        return None

    (current_class, current_title, first_range ) = parsed_class

    if current_class == DEBUG_CLASS:

        debug_lines.extend(
            [
                "",
                "ENTERED CLASS",
                f"Art Unit      : {current_art_unit}",
                f"Current Title : {current_title!r}",
                f"First Range   : {first_range!r}"
            ]
        )

    current_title = initialize_class( art_units, current_class, current_title)

    add_first_range( art_units, current_class, current_art_unit, first_range)

    return ( current_class, current_title, True, first_range is not None )
    
    
def handle_collecting_title( collecting_title, title_fragment, range_data, line, current_title, current_class, current_art_unit,

    art_units,debug_lines):

    if not collecting_title:

        return None

    #
    # Wrapped title
    #

    if range_data is None:

        current_title = append_title_fragment( current_title, line, art_units, current_class)

        if current_class == DEBUG_CLASS:

            debug_lines.append( f"UPDATED TITLE : {current_title!r}")

        return ( current_title, True )

    #
    # Title + range
    #

    if title_fragment:

        current_title = append_title_fragment( current_title, title_fragment, art_units, current_class)

    add_range( art_units, current_class, current_art_unit, range_data)

    return ( current_title, False)


def handle_remaining_range( range_data, current_class, current_art_unit, art_units):

    if not ( range_data and current_class and current_art_unit):

        return False

    add_range( art_units, current_class, current_art_unit, range_data)

    return True
    
    
def parse_art_units(text):
	
	print("Parsing Art Units...")
	
	lines = text.splitlines()
	
	current_art_unit = None
	current_class = None
	current_title = ""
	
	collecting_title = False
	
	#
	# True only when the first subclass range came from the
	# "Class ..." line. It allows wrapped title lines to follow.
	#
	class_line_had_range = False
	
	art_units = {}
	
	debug_lines = []
	
	for raw_line in lines:
	
		line = raw_line.strip()
	
		if not line:
			continue
	
		if should_skip_line(line):
			continue
	
		#
		# New Art Unit
		#
	
		new_state = handle_new_art_unit( line, current_class, debug_lines)
		
		if new_state:
		
			( current_art_unit, current_class, current_title, collecting_title, class_line_had_range
		
			) = new_state
		
			continue
	
		#
		# New Class
		#
	
		new_class = handle_new_class( line, art_units, current_art_unit, debug_lines)
		
		if new_class:
		
			(current_class, current_title, collecting_title, class_line_had_range) = new_class
		
			continue
	
		#
		# Parse subclass range
		#
	
		parsed_range = parse_range_line(line)
	
		if parsed_range:
	
			title_fragment, range_data = parsed_range
	
		else:
	
			title_fragment = ""
			range_data = None
	
		if current_class == DEBUG_CLASS:
	
			debug_lines.extend(
				[
					"",
					"LINE",
					f"Text         : {line!r}",
					f"Parsed Range : {parsed_range!r}",
					f"Collecting   : {collecting_title}",
					f"Current Title: {current_title!r}",
					f"Class Line Range: {class_line_had_range}"
				]
			)
	
		#
		# Continue wrapped title
		#
	
		title_result = handle_collecting_title( collecting_title, title_fragment, range_data, line, current_title, current_class,
		current_art_unit, art_units, debug_lines)
		
		if title_result:
		
			( current_title, collecting_title) = title_result
		
			continue
	
		#
		# Remaining subclass ranges
		#
	
		if handle_remaining_range( range_data, current_class, current_art_unit, art_units):
		
			continue
	
		report_unrecognized( current_art_unit, current_class, art_units[current_class]["title"], line)
	
	write_debug_file( debug_lines)
	
	print(f"Found {len(art_units)} classes.")
	
	return art_units


def save_json(data):

    print("Saving JSON...")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as file:
        json.dump(
            data,
            file,
            indent=4,
            ensure_ascii=False
        )

    print(f"Saved to {OUTPUT_FILE}")

	
def main():

    text = extract_pdf_text()

    art_units = parse_art_units(text)

    save_json(
        art_units
    )

    print("Done.")
    
    
if __name__ == "__main__":
    main()