import fitz
import json
import re
from pathlib import Path

PDF_FILE = Path("caau.pdf")
OUTPUT_FILE = Path("output/artUnits.json")
RANGE_TOKEN = (
    r"(?:"
    r"FOR\s+\d+"
    r"|DIG\s+\d+"
    r"|E\d+(?:\.\d+)?"
    r"|[0-9]+(?:\.[0-9]+)?(?:\s+[A-Z])?"
    r"|ALL"
    r")"
)

DEBUG_CLASS = "358"
DEBUG_FILE = Path("debug358.txt")

def extract_pdf_text():

    print("Reading PDF...")

    if not PDF_FILE.exists():

        raise FileNotFoundError(
            f"{PDF_FILE} not found."
        )

    pages = []

    with fitz.open(PDF_FILE) as document:

        for page in document:

            pages.append(
                page.get_text()
            )

    return "\n".join(pages)


def parse_range_line(line):

    line = line.rstrip()

    #
    # ALL
    #

    if line == "ALL":

        return (
            "",
            {
                "from": "ALL",
                "to": "ALL"
            }
        )

    #
    # title + from + to
    #

    match = re.match(

        rf"^(.*?)\s{{2,}}({RANGE_TOKEN})\s{{2,}}({RANGE_TOKEN})$",

        line

    )

    if match:

        return (

            match.group(1).strip(),

            {

                "from": match.group(2).strip(),

                "to": match.group(3).strip()

            }

        )

    #
    # title + single range
    #

    match = re.match(

        rf"^(.*?)\s{{2,}}({RANGE_TOKEN})$",

        line

    )

    if match:

        return (

            match.group(1).strip(),

            {

                "from": match.group(2).strip(),

                "to": match.group(2).strip()

            }

        )

    #
    # from + to
    #

    match = re.match(

        rf"^({RANGE_TOKEN})\s{{2,}}({RANGE_TOKEN})$",

        line

    )

    if match:

        return (

            "",

            {

                "from": match.group(1).strip(),

                "to": match.group(2).strip()

            }

        )

    #
    # single value
    #

    value = line.strip()

    if re.fullmatch(

        RANGE_TOKEN,

        value

    ):

        return (

            "",

            {

                "from": value,

                "to": value

            }

        )

    return None
    

def should_skip_line(line):

    line = line.strip()

    if not line:

        return True

    skip_patterns = [

        r"^November",

        r"^Generated by:",

        r"^CLASSES ARRANGED BY ART UNIT",

        r"^[IVX]+\s*-\s*\d+$",

        r"^Class Title$",

        r"^Subclass Ranges$",

        r"^From\s+To$",

        r"^Art Unit$",

        r"^Class$",

        r"^-+(\s+-+)*$"

    ]

    for pattern in skip_patterns:

        if re.match(
            pattern,
            line,
            re.IGNORECASE
        ):
            return True

    return False


def parse_art_unit(line):

    line = line.strip()

    match = re.match(

        r"^Art Unit\s+(\d+)$",

        line,

        re.IGNORECASE

    )

    if match:

        return match.group(1)

    return None


def parse_class(line):

	line = line.strip()
	
	match = re.match(
	
		r"^Class\s+([A-Z]?\s*\d+[A-Z]?|[A-Z]{2,}\d*|[A-Z]\d+[A-Z]?)\s+(.*)$",
	
		line,
	
		re.IGNORECASE
	
	)
	
	if not match:
	
		return None
	
	class_id = match.group(1).strip()
	
	remainder = match.group(2)
	
	#
	# Try to locate a range at the end.
	#
	
	range_match = re.search(
	
		rf"^(.*?)\s{{2,}}({RANGE_TOKEN})(?:\s{{2,}}({RANGE_TOKEN}))?$",
	
		remainder
	
	)
	
	if range_match:
	
		title = range_match.group(1).strip()
	
		first_range = {
	
			"from": range_match.group(2).strip(),
	
			"to": (
				range_match.group(3).strip()
				if range_match.group(3)
				else ""
			)
	
		}
	
	else:
	
		title = remainder.strip()
	
		first_range = None
	
	return class_id, title, first_range
 
    
def parse_art_units(text):
	
	print("Parsing Art Units...")
	
	lines = text.splitlines()
	
	current_art_unit = None
	current_class = None
	current_title = ""
	
	collecting_title = False
	
	#
	# True only when the first subclass range came from the
	# "Class ..." line. It allows wrapped title lines to follow.
	#
	class_line_had_range = False
	
	art_units = {}
	
	debug_lines = []
	
	for raw_line in lines:
	
		line = raw_line.strip()
	
		if not line:
			continue
	
		if should_skip_line(line):
			continue
	
		#
		# New Art Unit
		#
	
		art_unit = parse_art_unit(line)
	
		if art_unit:
	
			if current_class == DEBUG_CLASS:
	
				debug_lines.extend(
					[
						"",
						"=" * 70,
						f"NEW ART UNIT {art_unit}",
						"=" * 70
					]
				)
	
			current_art_unit = art_unit
			current_class = None
			current_title = ""
			collecting_title = False
			class_line_had_range = False
	
			continue
	
		#
		# New Class
		#
	
		parsed_class = parse_class(line)
	
		if parsed_class:
	
			(
				current_class,
				current_title,
				first_range
			) = parsed_class
	
			if current_class == DEBUG_CLASS:
	
				debug_lines.extend(
					[
						"",
						"ENTERED CLASS",
						f"Art Unit      : {current_art_unit}",
						f"Current Title : {current_title!r}",
						f"First Range   : {first_range!r}"
					]
				)
	
			if current_class not in art_units:
	
				art_units[current_class] = {
	
					"title": current_title,
	
					"ranges": []
	
				}
	
			else:
	
				current_title = art_units[current_class]["title"]
	
			collecting_title = True
	
			class_line_had_range = first_range is not None
	
			if first_range:
	
				first_range["artUnit"] = current_art_unit
	
				art_units[current_class]["ranges"].append(
					first_range
				)
	
			continue
	
		#
		# Parse subclass range
		#
	
		parsed_range = parse_range_line(line)
	
		if parsed_range:
	
			title_fragment, range_data = parsed_range
	
		else:
	
			title_fragment = ""
			range_data = None
	
		if current_class == DEBUG_CLASS:
	
			debug_lines.extend(
				[
					"",
					"LINE",
					f"Text         : {line!r}",
					f"Parsed Range : {parsed_range!r}",
					f"Collecting   : {collecting_title}",
					f"Current Title: {current_title!r}",
					f"Class Line Range: {class_line_had_range}"
				]
			)
	
		#
		# Continue wrapped title
		#
	
		if collecting_title:
	
			#
			# Ordinary wrapped title line
			#
	
			if range_data is None:
	
				fragment = " ".join(line.split())
				
				normalized_title = " ".join(current_title.split())
				
				if not normalized_title.endswith(fragment):
				
					current_title += " " + fragment
				
				art_units[current_class]["title"] = " ".join(
					current_title.split()
				)
	
				art_units[current_class]["title"] = " ".join(
					current_title.split()
				)
	
				if current_class == DEBUG_CLASS:
	
					debug_lines.append(
						f"UPDATED TITLE : {current_title!r}"
					)
	
				continue
	
			#
			# Title + range on same line
			#
	
			if title_fragment:
	
				fragment = " ".join(title_fragment.split())
				
				normalized_title = " ".join(current_title.split())
				
				if not normalized_title.endswith(fragment):
				
					current_title += " " + fragment
				
				art_units[current_class]["title"] = " ".join(
					current_title.split()
				)
	
				art_units[current_class]["title"] = " ".join(
					current_title.split()
				)
	
			#
			# If the first range already appeared on the
			# Class line, this is now the second range.
			# The title is complete.
			#
	
			collecting_title = False
	
			range_data["artUnit"] = current_art_unit
	
			art_units[current_class]["ranges"].append(
				range_data
			)
	
			continue
	
		#
		# Remaining subclass ranges
		#
	
		if (
	
			range_data
			and current_class
			and current_art_unit
	
		):
	
			range_data["artUnit"] = current_art_unit
	
			art_units[current_class]["ranges"].append(
				range_data
			)
	
			continue
	
		print(f"Warning: Unrecognized line: {line}")
	
	DEBUG_FILE.write_text(
		"\n".join(debug_lines),
		encoding="utf-8"
	)
	
	print(f"Found {len(art_units)} classes.")
	
	return art_units
    

def is_range_only(line):

    return re.match(

        r"^[A-Z0-9. ]+\s{2,}[A-Z0-9. ]+$",

        line

    ) is not None

def save_json(data):

    print("Saving JSON...")

    OUTPUT_FILE.parent.mkdir(

        parents=True,

        exist_ok=True

    )

    with open(

        OUTPUT_FILE,

        "w",

        encoding="utf-8"

    ) as file:

        json.dump(

            data,

            file,

            indent=4,

            ensure_ascii=False

        )

    print(

        f"Saved to {OUTPUT_FILE}"

    )

	
def main():

    text = extract_pdf_text()

    art_units = parse_art_units(text)

    save_json(
        art_units
    )

    print("Done.")
    
    
if __name__ == "__main__":
    main()