import fitz
import json
import re
from pathlib import Path

PDF_FILE = Path("caau.pdf")
OUTPUT_FILE = Path("output/artUnits.json")
RANGE_TOKEN = (
    r"(?:"
    r"FOR\s+\d+"
    r"|DIG\s+\d+"
    r"|E\d+(?:\.\d+)?"
    r"|[0-9]+(?:\.[0-9]+)?"
    r"|ALL"
    r")"
)

def extract_pdf_text():

    print("Reading PDF...")

    if not PDF_FILE.exists():

        raise FileNotFoundError(
            f"{PDF_FILE} not found."
        )

    pages = []

    with fitz.open(PDF_FILE) as document:

        for page in document:

            pages.append(
                page.get_text()
            )

    return "\n".join(pages)


def parse_range_line(line):

    line = line.rstrip()

    #
    # ALL
    #

    if line == "ALL":

        return (
            "",
            {
                "from": "ALL",
                "to": "ALL"
            }
        )

    #
    # title + from + to
    #
    # Example:
    #
    # APPLICATIONS     96      114
    #

    match = re.match(

        rf"^(.*?)\s{{2,}}({RANGE_TOKEN})\s{{2,}}({RANGE_TOKEN})$",

        line

    )

    if match:

        title = match.group(1).strip()

        return (

            title,

            {

                "from": match.group(2).strip(),

                "to": match.group(3).strip()

            }

        )

    #
    # from + to
    #

    match = re.match(

        r"^([A-Z0-9. ]+)\s{2,}([A-Z0-9. ]+)$",

        line

    )

    if match:

        return (

            "",

            {

                "from": match.group(1).strip(),

                "to": match.group(2).strip()

            }

        )

    #
    # single value
    #

    value = line.strip()

    if value:

        return (

            "",

            {

                "from": value,

                "to": value

            }

        )

    return None
    

def should_skip_line(line):

    line = line.strip()

    if not line:

        return True

    skip_patterns = [

        r"^November",

        r"^Generated by:",

        r"^CLASSES ARRANGED BY ART UNIT",

        r"^[IVX]+\s*-\s*\d+$",

        r"^Class Title$",

        r"^Subclass Ranges$",

        r"^From\s+To$",

        r"^Art Unit$",

        r"^Class$",

        r"^-+(\s+-+)*$"

    ]

    for pattern in skip_patterns:

        if re.match(
            pattern,
            line,
            re.IGNORECASE
        ):
            return True

    return False


def parse_art_unit(line):

    line = line.strip()

    match = re.match(

        r"^Art Unit\s+(\d+)$",

        line,

        re.IGNORECASE

    )

    if match:

        return match.group(1)

    return None


def parse_class(line):

	line = line.strip()
	
	match = re.match(
	
		r"^Class\s+([A-Z]?\s*\d+[A-Z]?|[A-Z]{2,}\d*|[A-Z]\d+[A-Z]?)\s+(.*)$",
	
		line,
	
		re.IGNORECASE
	
	)
	
	if not match:
	
		return None
	
	class_id = match.group(1).strip()
	
	remainder = match.group(2)
	
	#
	# Try to locate a range at the end.
	#
	
	range_match = re.search(
	
		rf"^(.*?)\s{{2,}}({RANGE_TOKEN})(?:\s{{2,}}({RANGE_TOKEN}))?$",
	
		remainder
	
	)
	
	if range_match:
	
		title = range_match.group(1).strip()
	
		first_range = {
	
			"from": range_match.group(2).strip(),
	
			"to": (
				range_match.group(3).strip()
				if range_match.group(3)
				else ""
			)
	
		}
	
	else:
	
		title = remainder.strip()
	
		first_range = None
	
	return class_id, title, first_range
 
    
def parse_art_units(text):
	
	print("Parsing Art Units...")
	
	lines = text.splitlines()
	
	current_art_unit = None
	
	current_class = None
	
	current_title = ""
	
	collecting_title = False
	
	art_units = {}
	
	for raw_line in lines:
	
		line = raw_line.strip()
	
		#
		# Skip blank lines
		#
	
		if not line:
	
			continue
	
		#
		# Skip page headers and footers
		#
	
		if should_skip_line(line):
	
			continue
	
		#
		# Detect a new Art Unit
		#
	
		art_unit = parse_art_unit(line)
		
		if art_unit:
		
			current_art_unit = art_unit
		
			current_class = None
		
			current_title = ""
		
			collecting_title = False
		
			continue
	
		#
		# Detect a new Class
		#
	
		parsed_class = parse_class(line)
		
		if parsed_class:
		
			(
		
				current_class,
		
				current_title,
		
				first_range
		
			) = parsed_class
		
			if current_class not in art_units:
		
				art_units[current_class] = {
		
					"title": current_title,
		
					"ranges": []
		
				}
		
			else:
		
				current_title = art_units[current_class]["title"]
		
			collecting_title = True
		
			if first_range:
		
				first_range["artUnit"] = current_art_unit
		
				art_units[current_class]["ranges"].append(
		
					first_range
		
				)
		
				collecting_title = False
		
			continue
	
		#
		# Try parsing a subclass range once
		#
	
		parsed_range = parse_range_line(line)
		
		if parsed_range:
		
			title_fragment, range_data = parsed_range
		
		else:
		
			title_fragment = ""
		
			range_data = None
	
		#
		# Continue reading a multi line class title
		#
	
		if collecting_title:
		
			if range_data:
		
				if title_fragment:
		
					current_title += " " + title_fragment
		
				art_units[current_class]["title"] = " ".join(
		
					current_title.split()
		
				)
		
				collecting_title = False
		
			else:
		
				current_title += " " + line
		
				art_units[current_class]["title"] = " ".join(
		
					current_title.split()
		
				)
		
				continue
	
		#
		# Store subclass range
		#
	
		if (
	
			range_data
	
			and current_class
	
			and current_art_unit
	
		):
	
			range_data["artUnit"] = current_art_unit
	
			art_units[current_class]["ranges"].append(
	
				range_data
	
			)
	
			continue
	
		#
		# Unknown line
		# Useful while developing.
		#
	
		print(f"Warning: Unrecognized line: {line}")
	
	print(
	
		f"Found {len(art_units)} classes."
	
	)
	
	return art_units


def is_range_only(line):

    return re.match(

        r"^[A-Z0-9. ]+\s{2,}[A-Z0-9. ]+$",

        line

    ) is not None

def save_json(data):

    print("Saving JSON...")

    OUTPUT_FILE.parent.mkdir(

        parents=True,

        exist_ok=True

    )

    with open(

        OUTPUT_FILE,

        "w",

        encoding="utf-8"

    ) as file:

        json.dump(

            data,

            file,

            indent=4,

            ensure_ascii=False

        )

    print(

        f"Saved to {OUTPUT_FILE}"

    )

	
def main():

    text = extract_pdf_text()

    art_units = parse_art_units(text)

    save_json(
        art_units
    )

    print("Done.")
    
    
if __name__ == "__main__":
    main()